name: 'doc.crds.dev warming'
description: 'Pull the new release of a custom resource definition from doc.crds.dev'
author: 'Mickael Stanislas (azrod)'
inputs:
  import_path:
    description: 'Package import path. If not set, github.com/<user>/<repo> is used as a default'
    required: false
    default: ''
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'download'
  color: 'blue'
